### ISSUE TITLE
fails to compile selector input[type=url]

### ISSUE THREAD

**Issue by gregor-rayman** [irundaia/sbt-sassify#30] opened 2017-10-10 21:07 UTC
When I try to compile the following (s)scc:

```css
input[type=url] {
  padding-left: 2rem;
}
```
the plugin fails with this error message:
 Error: Invalid CSS after "i": expected 1 selector or at-rule, was "input[type=url] {"

With the command line `sass` version 3.5.2 there is no problem. 

It seems that the problem is caused by the unquoted `url`. 
`input[type=email]`, 'input[type=fooooo]` and `input[type="url"]` compile without problems.

System: Ubuntu 16.04, 64bit

**Comment by irundaia** [comment] 2017-10-11 01:33
Compiler issues are typically caused by issues in libsass. This particur issue seems to have been [fixed already](https://github.com/sass/libsass/issues/2429).

However it hasn’t been released in a stable version yet (supposedly it has been [fixed](https://github.com/sass/libsass/issues/2456) in libsass version 3.5.0.beta3). Given that they’re using the 3.5 betas in node-sass, it might be better to switch to that version.

Could you try to install version 3.5.0.beta3 of libsass on your machine(s)? This will likely solve the issue for you since jna prefers to load system binaries over the packaged version.

**Comment by irundaia** [comment] 2018-02-25 06:09
@gregor-rayman, I've just released version 1.4.12. This version builds on uses a newer version of libsass. This contains the fix for your issue.

Could you verify that it has been fixed for you?

**Comment by irundaia** [comment] 2019-04-28 13:59
Closing due to inactivity

**Closed as completed by irundaia** 2019-04-28 13:59 UTC
